environment: dev
database:
  file: ./data/bookstore.db
  max_open_conns: 1
  max_idle_conns: 1
  conn_max_lifetime: 5m
logging:
  level: debug
  format: json
  output: file
  add_source: false
  max_size: 100
  max_age: 7
  max_backups: 10
  compress: false
  local_time: false
services:
  book:
    host: localhost
    port: 8081
    log_file: ./logs/book_service.log